block_type: "transformer"

transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 256
  decoder_layer: 6
  decoder_head: 2
  decoder_hidden: 256
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2
  decoder_dropout: 0.2

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5

variance_embedding:
  pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

gst:
  use_gst: False
  n_mel_channels: 80
  gst_tokens: 128
  gst_token_dim: 256
  gst_heads: 8
  gst_conv_layers: 6
  gst_conv_chans_list: [32, 32, 64, 64, 128, 128]
  gst_conv_kernel_size: 3
  gst_conv_stride: 2
  gst_gru_layers: 1
  gst_gru_units: 128

multi_speaker: False

max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "universal" # support  'LJSpeech', 'universal'
